write_behind: fix 2

diff --git a/recipes/write_behind/oracle/rs/wait-for-oracle b/recipes/write_behind/oracle/rs/wait-for-oracle
--- a/recipes/write_behind/oracle/rs/wait-for-oracle
+++ b/recipes/write_behind/oracle/rs/wait-for-oracle
@@ -12,12 +12,23 @@ if [[ $? != 0 ]]; then
 	exit 1
 fi
 
-for ((i = 0; i < $TIMEOUT; i++)); do
-	# this still can hang, so we really need to start it as a job and kill it
-	# if it does not come back within a second
-	echo "select * from dual" | sqlplus -S -L system/oracle@//$ORACLE:1521/xe > /dev/null 2>&1
-	[[ $? == 0 ]] && exit 0
-	sleep 1
-done
-echo "Oracle is not ready. Aborting."
-exit 1
+if [[ $DIAG != 1 ]]; then
+	for ((i = 0; i < $TIMEOUT; i++)); do
+		# this still can hang, so we really need to start it as a job and kill it
+		# if it does not come back within a second
+		echo "select * from dual" | sqlplus -S -L system/oracle@//$ORACLE:1521/xe > /dev/null 2>&1
+		[[ $? == 0 ]] && exit 0
+		sleep 1
+	done
+	echo "Oracle is not ready. Aborting."
+	exit 1
+else
+	for ((i = 0; 1 == 1; i++)); do
+		echo "select * from dual" | sqlplus -S -L system/oracle@//$ORACLE:1521/xe > /dev/null 2>&1
+		if [[ $? == 0 ]]; then
+			echo "Oracle ready after $i seconds."
+			exit 0
+		fi
+		sleep 1
+	done
+fi
