CircleCI: multiarch docker build

diff --git a/deps/readies/bin/getpy b/deps/readies/bin/getpy
--- a/deps/readies/bin/getpy
+++ b/deps/readies/bin/getpy
@@ -7,29 +7,29 @@ HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 [ "$VERBOSE" = "1" ] && set -x
 
 if [ ! -z $(command -v python) ]; then
-	[ "$(python --version 2>&1 | cut -d" " -f2 | cut -d. -f1)" = "2" ] && exit 0
+	[ "$(python --version 2>&1 | cut -d" " -f2 | cut -d. -f1)" = "3" ] && exit 0
 fi
 
-[ ! -z $(command -v python2) ] && exit 0
-[ ! -z $(command -v python2.7) ] && exit 0
+[ ! -z $(command -v python3) ] && exit 0
 
 [[ $CHECK == 1 ]] && exit 1
 
 if [ ! -z $(command -v apt-get) ]; then
 	runn apt-get -qq update
-	runn apt-get -qq install -y python
+	runn apt-get -qq install -y python3
 elif [ ! -z $(command -v dnf) ]; then
-	runn dnf install -y python2
+	runn dnf install -y python3
 elif [ ! -z $(command -v yum) ]; then
-	runn yum install -y python2
+	runn yum install -y epel-release
+	runn yum install -y python36
 elif [ ! -z $(command -v apk) ]; then
 	runn apk update
-	runn apk add python2
+	runn apk add python3
 elif [ ! -z $(command -v brew) ]; then
-	runn brew install python2
+	runn brew install python3
 fi
 
-if [ -z $(command -v python) ]; then
-	>&2 echo "Cannot install Python2. Aborting."
+if [ -z $(command -v python3) ]; then
+	>&2 echo "Cannot install Python3. Aborting."
 	exit 1
 fi
