New module dependency scheme

diff --git a/build/cpython/clean-pyenv b/build/cpython/clean-pyenv
--- a/build/cpython/clean-pyenv
+++ b/build/cpython/clean-pyenv
@@ -1,13 +1,23 @@
 #!/bin/bash
 
+HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
+ROOT=$(cd $HERE/../..; pwd)
+
 REDISLABS_DIR=/var/opt/redislabs
 
-if [[ -z $LOCAL ]]; then
-	echo "LOCAL argument undefined. Aborting."
+VERSION=$(NUMERIC=1 $ROOT/getver)
+if [[ -z $VERSION ]]; then
+	>&2 echo "Cannot determine module version. Aborting."
 	exit 1
 fi
 
-[[ -z $GLOBAL ]] && GLOBAL=$REDISLABS_DIR/lib/modules/python3
+if [[ -z $LOCAL ]]; then
+	>&2 echo "LOCAL argument undefined. Aborting."
+	exit 1
+fi
+
+# [[ -z $GLOBAL ]] && GLOBAL=$REDISLABS_DIR/lib/modules/python3
+[[ -z $GLOBAL ]] && GLOBAL=$REDISLABS_DIR/modules/rg/$VERSION/deps/python3
 
 [[ -e $LOCAL ]] && rm -rf $LOCAL
 [[ -d $GLOBAL ]]; rm -rf $GLOBAL
diff --git a/build/cpython/fix-pyenv b/build/cpython/fix-pyenv
--- a/build/cpython/fix-pyenv
+++ b/build/cpython/fix-pyenv
@@ -6,7 +6,15 @@ set -e
 HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 ROOT=$(cd $HERE/../..; pwd)
 
-cd /var/opt/redislabs/lib/modules/python3/.venv
+REDISLABS_DIR=/var/opt/redislabs
+
+VERSION=$(NUMERIC=1 $ROOT/getver)
+if [[ -z $VERSION ]]; then
+	>&2 echo "Cannot determine module version. Aborting."
+	exit 1
+fi
+
+cd $REDISLABS_DIR/modules/rg/$VERSION/deps/python3/.venv
 
 # fix shebangs
 $ROOT/deps/cpython/Tools/scripts/pathfix.py -n -i "/usr/bin/env python" . bin/* > /dev/null 2>&1 || true
@@ -22,7 +30,7 @@ fi
 
 # fix activate scripts
 for f in `grep -ril '\.venv' bin/activate*` .project; do
-	sed -i "s/\(['\"]\).*\(\/redislabs\/lib\/modules\/python3\)/\1\/var\/opt\2/" $f
+	sed -i "s/\(['\"]\).*\(\/redislabs\/lib\/modules\/rg\)/\1\/var\/opt\2/" $f
 done
 
 exit 0
diff --git a/build/cpython/install-pyenv b/build/cpython/install-pyenv
--- a/build/cpython/install-pyenv
+++ b/build/cpython/install-pyenv
@@ -5,7 +5,15 @@ set -e
 HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 ROOT=$(cd $HERE/../..; pwd)
 
-[[ -z $PYTHON_ROOT ]] && PYTHON_ROOT=/var/opt/redislabs/lib/modules/python3
+REDISLABS_DIR=/var/opt/redislabs
+
+VERSION=$(NUMERIC=1 $ROOT/getver)
+if [[ -z $VERSION ]]; then
+	>&2 echo "Cannot determine module version. Aborting."
+	exit 1
+fi
+
+[[ -z $PYTHON_ROOT ]] && PYTHON_ROOT=$REDISLABS_DIR/modules/rg/$VERSION/deps/python3
 PYTHON=$PYTHON_ROOT/bin/python3
 
 cp $HERE/Pipfile* $PYTHON_ROOT
diff --git a/build/cpython/prepare-python b/build/cpython/prepare-python
--- a/build/cpython/prepare-python
+++ b/build/cpython/prepare-python
@@ -3,17 +3,25 @@
 set -e
 
 HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
-. $HERE/../../deps/readies/shibumi/functions
+ROOT=$(cd $HERE/../..; pwd)
+
+. $ROOT/deps/readies/shibumi/functions
 
 REDISLABS_DIR=/var/opt/redislabs
 USER=`whoami`
 
-if [[ -z $LOCAL ]]; then
-	echo "LOCAL argument undefined. Aborting."
+VERSION=$(NUMERIC=1 $ROOT/getver)
+if [[ -z $VERSION ]]; then
+	>&2 echo "Cannot determine module version. Aborting."
 	exit 1
 fi
 
-[[ -z $GLOBAL ]] && GLOBAL=$REDISLABS_DIR/lib/modules/python3
+if [[ -z $LOCAL ]]; then
+	>&2 echo "LOCAL argument undefined. Aborting."
+	exit 1
+fi
+
+[[ -z $GLOBAL ]] && GLOBAL=$REDISLABS_DIR/modules/rg/$VERSION/deps/python3
 
 if [[ $PYENV_IN_SITU == 1 ]]; then
 	$SUDO find $(dirname $GLOBAL) -name $(basename $GLOBAL) -type l -delete
